name: "Release Note Writer"
description: "Generate a release note by comparing git changes using AI"
author: "combinatrix-ai"

inputs:
  compare_to:
    description: "Comparison mode: github_latest (compare with latest GitHub release), auto_tag (find and use latest git tag), or specified (use specific tag)"
    required: false
    default: "github_latest"
  tag:
    description: "Specific git tag to compare with HEAD. Required when compare_to is 'specified'."
    required: false
    default: ""
  model_name:
    description: "Optional model name for generating the release note. Defaults to 'gemini-2.0-flash-thinking-exp-01-21'."
    required: false
    default: "gemini-2.0-flash-thinking-exp-01-21"
  api_key:
    description: "Google Cloud API key for using the model."
    required: true

outputs:
  release_note:
    description: "The generated release note."

runs:
  using: "docker"
  image: "Dockerfile"
